### ISSUE TITLE
Client groups loading same group elements

### ISSUE THREAD

**Issue by petarkalafatic** [realvnc-labs/rport#1065] opened 2023-05-24 12:27 UTC
Problem loading more then 40 groups. 
Each time the "next" button is clicked it loads the same groups. I have 100+ created and can only get the first 40.

**Comment by thorstenkramm** [comment] 2023-05-24 13:04
@petarkalafatic I can't reproduce. Which frontend version do you use? 
0.9.12-3 is the latest.

Can you check with the browser dev tools, which offset it send when accessing the third page (groups 41-60)?

<img width="1166" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/5ffbca73-5875-44ac-92f5-5866f3292efd">

**Comment by petarkalafatic** [comment] 2023-05-24 13:36
![Screenshot from 2023-05-24 15-35-46](https://github.com/realvnc-labs/rport/assets/77074943/ff0d0bd7-c06d-4765-b096-d40f9e774ad4)


![Screenshot from 2023-05-24 15-35-19](https://github.com/realvnc-labs/rport/assets/77074943/292e63f8-3d50-4327-b11f-32d1661f9e99)

**Comment by thorstenkramm** [comment] 2023-05-24 13:42
@petarkalafatic 
Try updating the frontend to the latest version [frontend 0.9.12-3](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by thorstenkramm** [comment] 2023-05-24 14:13
Did you hard reload your browser? The screenshot looks like taken from an outdated version. 
With version 0.9.12-3 I can loop over all my groups and the offset is properly increased by 20. Tested with 140 client groups.

**Comment by qraleq** [comment] 2023-05-24 15:34
Hi @thorstenkramm , the server is on the latest version since some of the issues we previously had have been fixed, but I have the same issue as Petar does. We've hard reloaded the browser, but the issue is still there.

**Comment by qraleq** [comment] 2023-05-24 15:46
Just to make sure we're on the same page, this happens here:
![image](https://github.com/realvnc-labs/rport/assets/13619177/aaece3e5-cb9e-4825-97e7-f5cb8e739d19)

Even though I click on next page, offset is stuck at 20:
![image](https://github.com/realvnc-labs/rport/assets/13619177/a242c2c8-4402-468d-950e-da823daf409a)

**Comment by thorstenkramm** [comment] 2023-05-30 18:10
@qraleq This has been solved now.

Try updating the frontend to the latest version [frontend 0.9.12-5](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Closed by thorstenkramm** 2023-05-30 18:10 UTC

**Comment by petarkalafatic** [comment] 2023-05-31 08:09
Hi @thorstenkramm 
The issue is resolved in Chrome but I think it partially exists in Mozilla. 
When I go to the Client Groups in Mozilla I get the same issue as before but when I refresh the site with the open Client groups tab everything works fine.


![Screenshot from 2023-05-31 10-07-46](https://github.com/realvnc-labs/rport/assets/77074943/5fab7d42-9f46-4fc0-9613-e169ac74e213)

After tab refresh:
![Screenshot from 2023-05-31 10-08-21](https://github.com/realvnc-labs/rport/assets/77074943/74a5203f-3a5b-4582-9ce2-2f60a14410b5)

**Comment by thorstenkramm** [comment] 2023-05-31 08:25
@petarkalafatic This seems like a caching issue. The request parameters are not browser-specific. 
Try a hard reload (shift+reload) and check again what happens if you access the client groups.

**Comment by petarkalafatic** [comment] 2023-05-31 10:19
Did not help. I am using Linux so   "ctrl + shift + R" also "ctrl + F5"  do the hard reload but the issue stays persistent.

**Comment by petarkalafatic** [comment] 2023-05-31 10:25
Sorry @thorstenkramm

Mozilla's Incognito works fine. It's something with my caching. Will check the problem. 
Sorry
