### ISSUE TITLE
Logout button not working

### ISSUE THREAD

**Issue by SuperKali** [realvnc-labs/rport#1131] opened 2023-06-26 13:42 UTC
Hello, on the latest version the logout button not working.

Regards.

**Comment by SuperKali** [comment] 2023-06-26 14:54
Another problem that I have experienced is from mobile browser, I can’t click setting and the same problem of logout button.

https://streamable.com/ga3eq7

**Comment by thorstenkramm** [comment] 2023-06-26 15:02
@SuperKali Please do not submit two different issues under the same thread. This one is about the logout button.

**Comment by thorstenkramm** [comment] 2023-06-26 15:05
@SuperKali Which frontend version do you use? I cannot reproduce issues with the logout button. 

Try updating the frontend to the latest version [frontend 0.9.12-13](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

**Comment by SuperKali** [comment] 2023-06-26 15:08
@thorstenkramm i installed from 0 all with the main script:

`curl https://get.rport.io -o rport-install.sh
bash rport-install.sh
`

is not updated?

Regards.

**Comment by SuperKali** [comment] 2023-06-26 15:09
@thorstenkramm This was the version: rport-frontend-0.9.12-13-build-1141

**Comment by thorstenkramm** [comment] 2023-06-26 15:20
@SuperKali You are on the latest version. The installer always pulls the latest version. 
Can you record a video from the broken logout button? (From a desktop, not from a mobile)
That would help. Thank you.

**Closed** 2023-06-29 08:44 UTC
